### ISSUE TITLE
bug: "Couldn't find any data in embed page that we know how to parse" (play)

### ISSUE THREAD

**Issue by thaddeuskkr** [thaddeuskkr/Ethereal#15]
```
Error: Couldn't find any data in embed page that we know how to parse
    at /home/ubuntu/ethereal/node_modules/spotify-url-info/src/index.js:62:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/ubuntu/ethereal/util/resolveSpotify.js:5:18)
    at async Object.execute (/home/ubuntu/ethereal/commands/music/play.js:25:17)
    at async module.exports (/home/ubuntu/ethereal/events/client/interactionCreate.js:60:9)
```
**Command run:** `/play query: https://open.spotify.com/track/72jbDTw1piOOj770jWNeaG?si=9d37e9f4fb8d43e9`

First time ever that I've seen this error; interesting.

**Comment by thaddeuskkr** [comment]
Likely will be a wontfix, but will look into it a bit.
